name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: mkdir auto-standup.${{ matrix.os }} && go build -o auto-standup.${{ matrix.os }} -v ./...

      - name: Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact.${{ matrix.os }}
          path: auto-standup.${{ matrix.os }}/auto-standup.${{ matrix.os }}
