name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build_windows:
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go build -o auto-standup-${{ matrix.os }} main.go && ls -la

      - name: Test
        run: go test -v ./...

      - name: Zip artifact
        run: zip auto-standup-${{ matrix.os }}.zip auto-standup-${{ matrix.os }} && ls -la

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: auto-standup-${{ matrix.os }}
          path: auto-standup-${{ matrix.os }}.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v3
        with:
          name: auto-standup-ubuntu-latest
      - name: Debug step
        run: pwd && ls -la
      - name: Download macos artifact
        uses: actions/download-artifact@v3
        with:
          name: auto-standup-macos-latest
      - name: Debug step
        run: pwd && ls -la
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # TODO: add windows zip archive
          files: |
            auto-standup-ubuntu-latest.zip
            auto-standup-macos-latest.zip